import { drizzle } from "drizzle-orm/postgres-js";
import { eq } from "drizzle-orm";
import postgres from "postgres";
import * as schema from "./schema";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env" });

if (!process.env.SUPABASE_DATABASE_URL) {
  throw new Error("SUPABASE_DATABASE_URL is not set");
}

const nepalHospitals = [
  {
    name: "Bir Hospital",
    address: "Mahaboudha, Kathmandu",
    latitude: 27.7052,
    longitude: 85.3123,
    contactNumber: "+977-1-4221119",
    email: "info@birhospital.gov.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "Patan Hospital",
    address: "Lagankhel, Lalitpur",
    latitude: 27.6685,
    longitude: 85.3206,
    contactNumber: "+977-1-5522295",
    email: "info@pahs.edu.np",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Lalitpur",
    departments: [],
  },
  {
    name: "Bhaktapur Hospital",
    address: "Dudhpati, Bhaktapur",
    latitude: 27.6731,
    longitude: 85.4223,
    contactNumber: "+977-1-6610798",
    email: "info@bhaktapurhospital.gov.np",
    province: "Bagmati",
    district: "Bhaktapur",
    city: "Bhaktapur",
    departments: [],
  },
  {
    name: "Tribhuvan University Teaching Hospital (TUTH)",
    address: "Maharajguns, Kathmandu",
    latitude: 27.7344,
    longitude: 85.3315,
    contactNumber: "+977-1-4412303",
    email: "info@tuth.org.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "Paropakar Maternity and Women's Hospital",
    address: "Thapathali, Kathmandu",
    latitude: 27.6893,
    longitude: 85.3189,
    contactNumber: "+977-1-4260405",
    email: "info@pmwh.gov.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "B.P. Koirala Institute of Health Sciences",
    address: "Dharan, Sunsari",
    latitude: 26.8126,
    longitude: 87.2831,
    contactNumber: "+977-25-525555",
    email: "info@bpkihs.edu",
    province: "Koshi",
    district: "Sunsari",
    city: "Dharan",
    departments: [],
  },
  {
    name: "Dhulikhel Hospital",
    address: "Dhulikhel, Kavrepalanchok",
    latitude: 27.6253,
    longitude: 85.5398,
    contactNumber: "+977-11-490497",
    email: "dhulikhelhospital@kusms.edu.np",
    province: "Bagmati",
    district: "Kavrepalanchok",
    city: "Dhulikhel",
    departments: [],
  },
  {
    name: "Gandaki Medical College",
    address: "Pokhara, Kaski",
    latitude: 28.2255,
    longitude: 83.9961,
    contactNumber: "+977-61-538595",
    email: "info@gmc.edu.np",
    province: "Gandaki",
    district: "Kaski",
    city: "Pokhara",
    departments: [],
  },
  {
    name: "Nepal Mediciti Hospital",
    address: "Nakkhu, Lalitpur",
    latitude: 27.6635,
    longitude: 85.3045,
    contactNumber: "+977-1-4217766",
    email: "info@nepalmediciti.com",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Lalitpur",
    departments: [],
  },
  {
    name: "Norvic International Hospital",
    address: "Thapathali, Kathmandu",
    latitude: 27.6917,
    longitude: 85.3198,
    contactNumber: "+977-1-4258554",
    email: "info@norvichospital.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "Shahid Gangalal National Heart Centre",
    address: "Bansbari, Kathmandu",
    latitude: 27.7369,
    longitude: 85.3331,
    contactNumber: "+977-1-4371374",
    email: "info@sgnhc.org.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "Grande International Hospital",
    address: "Dhapasi, Kathmandu",
    latitude: 27.7516,
    longitude: 85.3275,
    contactNumber: "+977-1-5159266",
    email: "info@grandehospital.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "Civil Service Hospital",
    address: "Minbhawan, Kathmandu",
    latitude: 27.6896,
    longitude: 85.34,
    contactNumber: "+977-1-4107000",
    email: "info@civilservicehospital.org",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "Kanti Children's Hospital",
    address: "Maharajgunj, Kathmandu",
    latitude: 27.735,
    longitude: 85.332,
    contactNumber: "+977-1-4411550",
    email: "info@kantichildrenhospital.gov.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "Bhaktapur Cancer Hospital",
    address: "Bhaktapur",
    latitude: 27.673136,
    longitude: 85.422302,
    contactNumber: "+977-1-6611532",
    email: "info@bhaktapurcancerhospital.org",
    province: "Bagmati",
    district: "Bhaktapur",
    city: "Bhaktapur",
    departments: [],
  },
  {
    name: "Nepal Eye Hospital",
    address: "Tripureshwor, Kathmandu",
    latitude: 27.695,
    longitude: 85.315,
    contactNumber: "+977-1-4260813",
    email: "info@nepaleye.org.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [],
  },
  {
    name: "Lumbini Provincial Hospital",
    address: "Butwal, Rupandehi",
    latitude: 27.7006,
    longitude: 83.4484,
    contactNumber: "+977-71-540304",
    email: "lphospital@lumbini.gov.np",
    province: "Lumbini",
    district: "Rupandehi",
    city: "Butwal",
    departments: [],
  },
  {
    name: "Seti Provincial Hospital",
    address: "Dhangadhi, Kailali",
    latitude: 28.6926,
    longitude: 80.5905,
    contactNumber: "+977-91-521271",
    email: "info@setihospital.gov.np",
    province: "Sudurpashchim",
    district: "Kailali",
    city: "Dhangadhi",
    departments: [],
  },
  {
    name: "Tri Chandra Military Hospital",
    address: "Bhadrakali, Tudikhel, Kathmandu",
    latitude: 27.7037,
    longitude: 85.3135,
    contactNumber: "+977-1-4262000",
    email: "trichandramilitaryho5cvhjb@healthcare.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [
      "Dental",
      "Pediatrics",
      "Physiotherapy",
      "Pathology",
      "Radiotherapy",
    ],
  },
  {
    name: "Sukraraj Tropical & Infectious Disease Hospital",
    address: "Teku, Kathmandu",
    latitude: 27.689,
    longitude: 85.325,
    contactNumber: "+977-1-4253295",
    email: "sukrarajtropicalinfe5h5ke1@healthcare.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Infectious Diseases", "TB Control", "Emergency"],
  },
  {
    name: "Paropakar Maternity & Women's Hospital",
    address: "Thapathali, Kathmandu",
    latitude: 27.6895,
    longitude: 85.322,
    contactNumber: "+977-1-4246511",
    email: "paropakarmaternitywod42wgo@healthcare.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Obstetrics", "Gynecology", "Neonatology", "Family Planning"],
  },
  {
    name: "National Academy of Medical Sciences (Bir Hospital)",
    address: "Mahaboudha, Kathmandu",
    latitude: 27.7054,
    longitude: 85.3134,
    contactNumber: "+977-1-4221119",
    email: "admin@birhospital.gov.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["General Medicine", "Surgery", "Emergency", "Orthopedics"],
  },
  {
    name: "Patan Academy of Health Sciences (Patan Hospital)",
    address: "Lagankhel, Lalitpur",
    latitude: 27.6894,
    longitude: 85.3227,
    contactNumber: "+977-1-5522278",
    email: "patanacademyofhealth9ofysc@healthcare.np",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Lalitpur",
    departments: ["General Medicine", "Surgery", "Emergency"],
  },
  {
    name: "Karnali Academy of Health Sciences",
    address: "Jumla",
    latitude: 29.2853,
    longitude: 82.1827,
    contactNumber: "+977-87-520199",
    email: "karnaliacademyofheal35aszv@hospital.com.np",
    province: "Karnali",
    district: "Jumla",
    city: "Jumla",
    departments: ["General Medicine", "Surgery", "Obstetrics"],
  },
  {
    name: "Rapti Academy of Health Sciences",
    address: "Ghorahi, Dang",
    latitude: 28.0369,
    longitude: 82.1025,
    contactNumber: "",
    email: "raptiacademyofhealth6oul21@info.np",
    province: "Lumbini",
    district: "Dang",
    city: "Ghorahi",
    departments: ["Medicine", "Surgery"],
  },
  {
    name: "Pokhara Academy of Health Sciences",
    address: "Pokhara, Kaski",
    latitude: 28.2096,
    longitude: 83.9856,
    contactNumber: "",
    email: "pokharaacademyofhealjc9bz3@yahoo.com",
    province: "Gandaki",
    district: "Kaski",
    city: "Pokhara",
    departments: ["Medicine", "Surgery"],
  },
  {
    name: "Madan Bhandari Academy of Health Sciences",
    address: "Hetauda, Makwanpur",
    latitude: 27.4268,
    longitude: 85.032,
    contactNumber: "",
    email: "madanbhandariacademyn9rdgc@gmail.com",
    province: "Bagmati",
    district: "Makwanpur",
    city: "Hetauda",
    departments: ["Medicine", "Surgery"],
  },
  {
    name: "Madhesh Institute of Health Sciences",
    address: "Janakpur, Dhanusha",
    latitude: 26.7289,
    longitude: 85.9249,
    contactNumber: "",
    email: "madheshinstituteofheomh10w@info.np",
    province: "Madhesh",
    district: "Dhanusha",
    city: "Janakpur",
    departments: ["Medicine", "Obstetrics"],
  },
  {
    name: "Nepal Army Institute of Health Science",
    address: "Sunsari",
    latitude: 26.5214,
    longitude: 87.2835,
    contactNumber: "+977-25-526678",
    email: "nepalarmyinstituteofnxqn73@healthcare.np",
    province: "Koshi",
    district: "Sunsari",
    city: "Dharan",
    departments: ["Military Medicine", "Surgery"],
  },
  {
    name: "Manmohan Cardiothoracic and Vascular Transplant Center",
    address: "Rangikhet, Kathmandu",
    latitude: 27.734,
    longitude: 85.35,
    contactNumber: "+977-1-4375342",
    email: "manmohancardiothoracfz12xh@info.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Cardiothoracic Surgery", "Vascular Surgery"],
  },
  {
    name: "B.P. Koirala Memorial Cancer Hospital",
    address: "Bharatpur, Chitwan",
    latitude: 27.6333,
    longitude: 84.4333,
    contactNumber: "+977-56-520155",
    email: "bpkoiralamemorialcan801g09@yahoo.com",
    province: "Bagmati",
    district: "Chitwan",
    city: "Bharatpur",
    departments: ["Oncology", "Radiotherapy", "Surgical Oncology"],
  },
  {
    name: "Shahid Gangalal National Heart Center",
    address: "Basundhara, Kathmandu",
    latitude: 27.7275,
    longitude: 85.3467,
    contactNumber: "+977-1-5970018",
    email: "info@sglnhc.org.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Cardiology", "Cardiac Surgery"],
  },
  {
    name: "Mechi Provincial Hospital",
    address: "Bhadrapur, Jhapa",
    latitude: 26.3381,
    longitude: 88.1003,
    contactNumber: "+977-23-520024",
    email: "mechiprovincialhospihb2evz@info.np",
    province: "Koshi",
    district: "Jhapa",
    city: "Bhadrapur",
    departments: ["General Medicine", "Surgery", "Emergency", "Obstetrics"],
  },
  {
    name: "Koshi Provincial Hospital",
    address: "Biratnagar, Morang",
    latitude: 26.4525,
    longitude: 87.2718,
    contactNumber: "+977-21-524043",
    email: "info@koshihospital.gov.np",
    province: "Koshi",
    district: "Morang",
    city: "Biratnagar",
    departments: ["General Medicine", "Surgery", "Emergency"],
  },
  {
    name: "Sagarmatha Provincial Hospital",
    address: "Rajbiraj, Saptari",
    latitude: 26.5333,
    longitude: 86.75,
    contactNumber: "+977-31-520199",
    email: "sagarmathaprovincialk5ez8c@hospital.com.np",
    province: "Madhesh",
    district: "Saptari",
    city: "Rajbiraj",
    departments: ["General Medicine", "Surgery"],
  },
  {
    name: "Gaur Provincial Hospital",
    address: "Gaur, Rautahat",
    latitude: 26.8189,
    longitude: 85.2839,
    contactNumber: "+977-55-580148",
    email: "gaurhospitalp2@gmail.com",
    province: "Madhesh",
    district: "Rautahat",
    city: "Gaur",
    departments: ["General Medicine", "Emergency"],
  },
  {
    name: "Jaleshwor Hospital",
    address: "Jaleshwor, Mahottari",
    latitude: 26.7833,
    longitude: 85.8,
    contactNumber: "",
    email: "jaleshworhospitalrois5f@hospital.com.np",
    province: "Madhesh",
    district: "Mahottari",
    city: "Jaleshwor",
    departments: ["General Medicine"],
  },
  {
    name: "Janakpur Provincial Hospital",
    address: "Janakpur, Dhanusha",
    latitude: 26.7289,
    longitude: 85.9249,
    contactNumber: "+977-41-520133",
    email: "janakpurprovincialhou7nk89@info.np",
    province: "Madhesh",
    district: "Dhanusha",
    city: "Janakpur",
    departments: ["General Medicine", "Surgery"],
  },
  {
    name: "Kalaiya Provincial Hospital",
    address: "Kalaiya, Bara",
    latitude: 27.0214,
    longitude: 85.0127,
    contactNumber: "",
    email: "kalaiyaprovincialhosn9qv6p@healthcare.np",
    province: "Madhesh",
    district: "Bara",
    city: "Kalaiya",
    departments: ["General Medicine"],
  },
  {
    name: "Malangwa Provincial Hospital",
    address: "Malangwa, Sarlahi",
    latitude: 26.8333,
    longitude: 85.5667,
    contactNumber: "",
    email: "malangwaprovincialho9c9dmg@info.np",
    province: "Madhesh",
    district: "Sarlahi",
    city: "Malangwa",
    departments: ["General Medicine"],
  },
  {
    name: "Narayani Provincial Hospital",
    address: "Birgunj, Parsa",
    latitude: 27.0104,
    longitude: 84.8753,
    contactNumber: "+977-51-521683",
    email: "narayaniprovincialhoam467u@healthcare.np",
    province: "Madhesh",
    district: "Parsa",
    city: "Birgunj",
    departments: ["General Medicine", "Surgery"],
  },
  {
    name: "Siraha Provincial Hospital",
    address: "Siraha, Siraha",
    latitude: 26.6333,
    longitude: 86.2,
    contactNumber: "",
    email: "sirahaprovincialhosp4rz8u4@healthcare.np",
    province: "Madhesh",
    district: "Siraha",
    city: "Siraha",
    departments: ["General Medicine"],
  },
  {
    name: "Hetauda Provincial Hospital",
    address: "Hetauda, Makwanpur",
    latitude: 27.4268,
    longitude: 85.032,
    contactNumber: "+977-57-520026",
    email: "hospital.hetauda@gmail.com",
    province: "Bagmati",
    district: "Makwanpur",
    city: "Hetauda",
    departments: ["General Medicine", "Surgery"],
  },
  {
    name: "Pokhara Provincial Hospital",
    address: "Pokhara, Kaski",
    latitude: 28.2096,
    longitude: 83.9856,
    contactNumber: "+977-61-530399",
    email: "pokharaprovincialhosqt0ekc@info.np",
    province: "Gandaki",
    district: "Kaski",
    city: "Pokhara",
    departments: ["General Medicine", "Emergency"],
  },
  {
    name: "Dhaulagiri Provincial Hospital",
    address: "Baglung, Baglung",
    latitude: 28.2667,
    longitude: 83.6,
    contactNumber: "",
    email: "dhaulagiriprovincialnt2mrd@info.np",
    province: "Gandaki",
    district: "Baglung",
    city: "Baglung",
    departments: ["General Medicine"],
  },
  {
    name: "Madhyabindu Provincial Hospital",
    address: "Madhyabindu, Nawalparasi",
    latitude: 27.6667,
    longitude: 84.1667,
    contactNumber: "",
    email: "madhyabinduprovinciar0w9um@gmail.com",
    province: "Gandaki",
    district: "Nawalparasi",
    city: "Madhyabindu",
    departments: ["General Medicine"],
  },
  {
    name: "Rapti Provincial Hospital",
    address: "Ghorahi, Dang",
    latitude: 28.0369,
    longitude: 82.1025,
    contactNumber: "",
    email: "raptiprovincialhospi8j0opd@yahoo.com",
    province: "Lumbini",
    district: "Dang",
    city: "Ghorahi",
    departments: ["General Medicine"],
  },
  {
    name: "Bheri Provincial Hospital",
    address: "Nepalgunj, Banke",
    latitude: 28.05,
    longitude: 81.6167,
    contactNumber: "+977-23-520024",
    email: "bheriprovincialhospigs2xcm@yahoo.com",
    province: "Koshi",
    district: "Jhapa",
    city: "Bhadrapur",
    departments: ["General Medicine", "Surgery", "Emergency", "Obstetrics"],
  },
  {
    name: "Karnali Provincial Hospital",
    address: "Surkhet, Karnali",
    latitude: 28.5833,
    longitude: 81.6333,
    contactNumber: "",
    email: "karnaliprovincialhos45nyyg@gmail.com",
    province: "Karnali",
    district: "Surkhet",
    city: "Birendranagar",
    departments: ["General Medicine"],
  },
  {
    name: "Mahakali Provincial Hospital",
    address: "Mahendranagar, Kanchanpur",
    latitude: 28.7667,
    longitude: 80.1333,
    contactNumber: "+977-99-521201",
    email: "mahakaliprovincialhoi2y9ll@hospital.com.np",
    province: "Sudurpashchim",
    district: "Kanchanpur",
    city: "Mahendranagar",
    departments: ["General Medicine"],
  },
  {
    name: "Ayurveda Teaching Hospital",
    address: "Kirtipur, Kathmandu",
    latitude: 27.6786,
    longitude: 85.2763,
    contactNumber: "+977-1-4335847",
    email: "info@ath.tu.edu.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Kayachikitsa", "Panchakarma", "Shalya", "Shalakya"],
  },
  {
    name: "Patan Mental Hospital",
    address: "Lagankhel, Lalitpur",
    latitude: 27.685,
    longitude: 85.32,
    contactNumber: "+977-1-5523983",
    email: "patanmentalhospital61s1ii@yahoo.com",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Lalitpur",
    departments: ["Psychiatry", "Mental Health", "Counseling"],
  },
  {
    name: "National Cardiac Center",
    address: "Paknajol, Kathmandu",
    latitude: 27.709,
    longitude: 85.315,
    contactNumber: "+977-1-4256697",
    email: "nationalcardiaccente2jlpjc@info.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Cardiology", "Cardiac Surgery"],
  },
  {
    name: "Teku Infectious Disease Hospital",
    address: "Teku, Kathmandu",
    latitude: 27.689,
    longitude: 85.325,
    contactNumber: "+977-1-4253295",
    email: "tekuinfectiousdiseastjd3nv@healthcare.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Infectious Diseases", "TB Control", "Emergency"],
  },
  {
    name: "Paropakar Maternity Hospital",
    address: "Thapathali, Kathmandu",
    latitude: 27.6895,
    longitude: 85.322,
    contactNumber: "+977-1-4246511",
    email: "paropakarmaternityho96xytm@yahoo.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Obstetrics", "Gynecology", "Neonatology"],
  },
  {
    name: "Ganga Lal Hospital",
    address: "Basundhara, Kathmandu",
    latitude: 27.7275,
    longitude: 85.3467,
    contactNumber: "+977-1-5970018",
    email: "info@sglnhc.org.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Cardiology", "Cardiac Surgery"],
  },
  {
    name: "Til Ganga Eye Hospital",
    address: "Gaushala, Kathmandu",
    latitude: 27.71,
    longitude: 85.35,
    contactNumber: "+977-1-5970048",
    email: "info@tilganga.org",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Ophthalmology", "Cornea", "Retina"],
  },
  {
    name: "Manmohan Cardiothoracic and Vascular Hospital",
    address: "Rangikhet, Kathmandu",
    latitude: 27.734,
    longitude: 85.35,
    contactNumber: "+977-1-4375342",
    email: "manmohancardiothoracbk19m5@gmail.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Cardiothoracic", "Vascular Surgery", "Transplant"],
  },
  {
    name: "Bharatpur Cancer Hospital",
    address: "Bharatpur, Chitwan",
    latitude: 27.6333,
    longitude: 84.4333,
    contactNumber: "+977-56-520155",
    email: "bharatpurcancerhospiiaectj@hospital.com.np",
    province: "Bagmati",
    district: "Chitwan",
    city: "Bharatpur",
    departments: ["Oncology", "Radiotherapy"],
  },
  {
    name: "Sushil Koirala Prakhar Cancer Hospital",
    address: "Bharatpur, Chitwan",
    latitude: 27.65,
    longitude: 84.42,
    contactNumber: "",
    email: "sushilkoiralaprakhara38hnu@hospital.com.np",
    province: "Bagmati",
    district: "Chitwan",
    city: "Bharatpur",
    departments: ["Oncology"],
  },
  {
    name: "Human Organ Transplant Centre",
    address: "Kathmandu",
    latitude: 27.7172,
    longitude: 85.324,
    contactNumber: "",
    email: "humanorgantransplantz4xkg7@gmail.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Organ Transplant", "Nephrology"],
  },
  {
    name: "National Tuberculosis Control Center",
    address: "Thimi, Bhaktapur",
    latitude: 27.67,
    longitude: 85.4,
    contactNumber: "+977-1-6614600",
    email: "nationaltuberculosisrk4d0e@hospital.com.np",
    province: "Bagmati",
    district: "Bhaktapur",
    city: "Thimi",
    departments: ["Tuberculosis", "Respiratory"],
  },
  {
    name: "G.P. Koirala National Center For Respiratory Diseases",
    address: "Kathmandu",
    latitude: 27.7,
    longitude: 85.33,
    contactNumber: "",
    email: "gpkoiralanationalcen607lxi@yahoo.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Respiratory", "Pulmonology"],
  },
  {
    name: "Mechi Eye Hospital",
    address: "Bhadrapur, Jhapa",
    latitude: 26.3381,
    longitude: 88.1003,
    contactNumber: "",
    email: "mechieyehospital6wilkx@info.np",
    province: "Koshi",
    district: "Jhapa",
    city: "Bhadrapur",
    departments: ["Ophthalmology"],
  },
  {
    name: "Golchha Eye Hospital",
    address: "Nepalgunj",
    latitude: 28.05,
    longitude: 81.6167,
    contactNumber: "",
    email: "golchhaeyehospitalke3p57@hospital.com.np",
    province: "Karnali",
    district: "Banke",
    city: "Nepalgunj",
    departments: ["Ophthalmology"],
  },
  {
    name: "Sagarmatha Choudhary Eye Hospital",
    address: "Lahan, Siraha",
    latitude: 26.7167,
    longitude: 86.4833,
    contactNumber: "",
    email: "sagarmathachoudharyesydj4z@gmail.com",
    province: "Madhesh",
    district: "Siraha",
    city: "Lahan",
    departments: ["Ophthalmology"],
  },
  {
    name: "Kedia Eye Hospital",
    address: "Pokhara",
    latitude: 28.2096,
    longitude: 83.9856,
    contactNumber: "",
    email: "kediaeyehospital0bhqjj@hospital.com.np",
    province: "Gandaki",
    district: "Kaski",
    city: "Pokhara",
    departments: ["Ophthalmology"],
  },
  {
    name: "Himalayan Eye Hospital",
    address: "Pokhara",
    latitude: 28.24,
    longitude: 83.97,
    contactNumber: "",
    email: "himalayaneyehospital4etm40@healthcare.np",
    province: "Gandaki",
    district: "Kaski",
    city: "Pokhara",
    departments: ["Ophthalmology"],
  },
  {
    name: "Rapti Eye Hospital",
    address: "Ghorahi, Dang",
    latitude: 28.0369,
    longitude: 82.1025,
    contactNumber: "",
    email: "raptieyehospitals5usxh@info.np",
    province: "Lumbini",
    district: "Dang",
    city: "Ghorahi",
    departments: ["Ophthalmology"],
  },
  {
    name: "Fatte Eye Hospital",
    address: "Dhangadhi, Kailali",
    latitude: 28.7,
    longitude: 80.5833,
    contactNumber: "",
    email: "fatteeyehospitalsbwnau@hospital.com.np",
    province: "Sudurpashchim",
    district: "Kailali",
    city: "Dhangadhi",
    departments: ["Ophthalmology"],
  },
  {
    name: "Geta Eye Hospital",
    address: "Kailali",
    latitude: 28.75,
    longitude: 80.65,
    contactNumber: "",
    email: "getaeyehospitalp7ersi@info.np",
    province: "Sudurpashchim",
    district: "Kailali",
    city: "Geta",
    departments: ["Ophthalmology"],
  },
  {
    name: "Rasuwa District Hospital",
    address: "Dhumrapokhari, Rasuwa",
    latitude: 28.0,
    longitude: 85.1333,
    contactNumber: "+977-10-680027",
    email: "rasuwadistricthospit8mph8w@healthcare.np",
    province: "Bagmati",
    district: "Rasuwa",
    city: "Dhumrapokhari",
    departments: ["General Medicine", "Emergency", "Obstetrics"],
  },
  {
    name: "Manang District Hospital",
    address: "Chame, Manang",
    latitude: 28.5333,
    longitude: 84.3333,
    contactNumber: "",
    email: "manangdistricthospitzha5la@healthcare.np",
    province: "Gandaki",
    district: "Manang",
    city: "Chame",
    departments: ["General Medicine"],
  },
  {
    name: "Mustang District Hospital",
    address: "Jomsom, Mustang",
    latitude: 28.7667,
    longitude: 83.7333,
    contactNumber: "",
    email: "mustangdistricthospizyfev9@gmail.com",
    province: "Gandaki",
    district: "Mustang",
    city: "Jomsom",
    departments: ["General Medicine"],
  },
  {
    name: "Bajura District Hospital",
    address: "Kolti, Bajura",
    latitude: 29.5,
    longitude: 81.1833,
    contactNumber: "",
    email: "bajuradistricthospituq6e93@hospital.com.np",
    province: "Sudurpashchim",
    district: "Bajura",
    city: "Kolti",
    departments: ["General Medicine", "Emergency"],
  },
  {
    name: "Mugu District Hospital",
    address: "Gamgadhi, Mugu",
    latitude: 29.3667,
    longitude: 82.1667,
    contactNumber: "",
    email: "mugudistricthospital1h7xbn@info.np",
    province: "Karnali",
    district: "Mugu",
    city: "Gamgadhi",
    departments: ["General Medicine"],
  },
  {
    name: "Dolpa District Hospital",
    address: "Dunai, Dolpa",
    latitude: 28.5333,
    longitude: 82.8333,
    contactNumber: "",
    email: "dolpadistricthospitaedez23@info.np",
    province: "Karnali",
    district: "Dolpa",
    city: "Dunai",
    departments: ["General Medicine"],
  },
  {
    name: "Humla District Hospital",
    address: "Simikot, Humla",
    latitude: 31.5333,
    longitude: 81.8167,
    contactNumber: "",
    email: "humladistricthospita4kr6bw@hospital.com.np",
    province: "Karnali",
    district: "Humla",
    city: "Simikot",
    departments: ["General Medicine"],
  },
  {
    name: "Solu District Hospital",
    address: "Salleri, Solukhumbu",
    latitude: 27.4833,
    longitude: 86.6333,
    contactNumber: "",
    email: "soludistricthospitalqm5eni@healthcare.np",
    province: "Koshi",
    district: "Solukhumbu",
    city: "Salleri",
    departments: ["General Medicine"],
  },
  {
    name: "Taplejung District Hospital",
    address: "Phidim, Taplejung",
    latitude: 27.1,
    longitude: 87.8167,
    contactNumber: "",
    email: "taplejungdistricthosnup3nr@healthcare.np",
    province: "Koshi",
    district: "Taplejung",
    city: "Phidim",
    departments: ["General Medicine", "Emergency"],
  },
  {
    name: "Tehrathum District Hospital",
    address: "Myanglung, Tehrathum",
    latitude: 27.0333,
    longitude: 87.7,
    contactNumber: "",
    email: "tehrathumdistricthos3l1fzs@info.np",
    province: "Koshi",
    district: "Tehrathum",
    city: "Myanglung",
    departments: ["General Medicine"],
  },
  {
    name: "Jiri Hospital",
    address: "Jiri, Dolakha",
    latitude: 27.6333,
    longitude: 86.2333,
    contactNumber: "+977-49-580013",
    email: "jirihospitalod6jt8@info.np",
    province: "Bagmati",
    district: "Dolakha",
    city: "Jiri",
    departments: ["General Medicine", "Surgery"],
  },
  {
    name: "Lamjung District Hospital",
    address: "Besisahar, Lamjung",
    latitude: 28.2333,
    longitude: 84.3667,
    contactNumber: "",
    email: "lamjungdistricthospi5w9j7m@hospital.com.np",
    province: "Gandaki",
    district: "Lamjung",
    city: "Besisahar",
    departments: ["General Medicine"],
  },
  {
    name: "Damauli Hospital",
    address: "Damauli, Tanahun",
    latitude: 28.0333,
    longitude: 84.3167,
    contactNumber: "",
    email: "damaulihospitali0j3r9@gmail.com",
    province: "Gandaki",
    district: "Tanahun",
    city: "Damauli",
    departments: ["General Medicine"],
  },
  {
    name: "Parbat Hospital",
    address: "Kusma, Parbat",
    latitude: 28.2333,
    longitude: 83.6667,
    contactNumber: "",
    email: "parbathospitalxmthxg@gmail.com",
    province: "Gandaki",
    district: "Parbat",
    city: "Kusma",
    departments: ["General Medicine"],
  },
  {
    name: "Beni Hospital",
    address: "Beni, Myagdi",
    latitude: 28.4167,
    longitude: 83.5,
    contactNumber: "",
    email: "benihospital6w6sj6@yahoo.com",
    province: "Gandaki",
    district: "Myagdi",
    city: "Beni",
    departments: ["General Medicine"],
  },
  {
    name: "Kapilvastu Hospital",
    address: "Tansen, Palpa",
    latitude: 27.8667,
    longitude: 83.55,
    contactNumber: "",
    email: "kapilvastuhospitalwr4gz6@healthcare.np",
    province: "Lumbini",
    district: "Palpa",
    city: "Tansen",
    departments: ["General Medicine"],
  },
  {
    name: "Rukum District Hospital",
    address: "Rukumkot, Rukum",
    latitude: 28.1167,
    longitude: 82.0833,
    contactNumber: "",
    email: "rukumdistricthospita28uscx@gmail.com",
    province: "Lumbini",
    district: "Rukum Paschim",
    city: "Rukumkot",
    departments: ["General Medicine"],
  },
  {
    name: "Jajarkot Hospital",
    address: "Khalanga, Jajarkot",
    latitude: 28.2667,
    longitude: 81.6833,
    contactNumber: "",
    email: "jajarkothospitalo8gsfi@healthcare.np",
    province: "Karnali",
    district: "Jajarkot",
    city: "Khalanga",
    departments: ["General Medicine"],
  },
  {
    name: "Dailekh District Hospital",
    address: "Narayan, Dailekh",
    latitude: 28.7667,
    longitude: 81.5833,
    contactNumber: "",
    email: "dailekhdistricthospip6bxau@info.np",
    province: "Karnali",
    district: "Dailekh",
    city: "Narayan",
    departments: ["General Medicine"],
  },
  {
    name: "Accham District Hospital",
    address: "Mangalsen, Accham",
    latitude: 29.1833,
    longitude: 81.2333,
    contactNumber: "",
    email: "acchamdistricthospitj58shz@info.np",
    province: "Sudurpashchim",
    district: "Accham",
    city: "Mangalsen",
    departments: ["General Medicine"],
  },
  {
    name: "Salyan District Hospital",
    address: "Salyan, Salyan",
    latitude: 28.3833,
    longitude: 82.1333,
    contactNumber: "",
    email: "salyandistricthospitgwp2ze@gmail.com",
    province: "Karnali",
    district: "Salyan",
    city: "Salyan",
    departments: ["General Medicine"],
  },
  {
    name: "Baitadi District Hospital",
    address: "Dasharathchand, Baitadi",
    latitude: 29.4,
    longitude: 80.4667,
    contactNumber: "",
    email: "baitadidistricthospigpcb0m@hospital.com.np",
    province: "Sudurpashchim",
    district: "Baitadi",
    city: "Dasharathchand",
    departments: ["General Medicine"],
  },
  {
    name: "Darchula District Hospital",
    address: "Khuloi, Darchula",
    latitude: 29.8167,
    longitude: 80.5833,
    contactNumber: "",
    email: "darchuladistricthospl9lp6p@hospital.com.np",
    province: "Sudurpashchim",
    district: "Darchula",
    city: "K huloi",
    departments: ["General Medicine"],
  },
  {
    name: "Ramechhap Hospital",
    address: "Manthali, Ramechhap",
    latitude: 27.3833,
    longitude: 86.0833,
    contactNumber: "",
    email: "ramechhaphospital44j0d9@gmail.com",
    province: "Bagmati",
    district: "Ramechhap",
    city: "Manthali",
    departments: ["General Medicine"],
  },
  {
    name: "Panchthar District Hospital",
    address: "Phidim, Panchthar",
    latitude: 27.1167,
    longitude: 87.9333,
    contactNumber: "",
    email: "panchthardistricthos88mb9e@hospital.com.np",
    province: "Koshi",
    district: "Panchthar",
    city: "Phidim",
    departments: ["General Medicine"],
  },
  {
    name: "Ilam District Hospital",
    address: "Ilam Bazar, Ilam",
    latitude: 26.9167,
    longitude: 87.5333,
    contactNumber: "",
    email: "ilamdistricthospitalmnd3ad@gmail.com",
    province: "Koshi",
    district: "Ilam",
    city: "Ilam",
    departments: ["General Medicine"],
  },
  {
    name: "Dhankuta District Hospital",
    address: "Hile, Dhankuta",
    latitude: 27.0,
    longitude: 87.3333,
    contactNumber: "9842042974",
    email: "santoshkirat1988@gmail.com",
    province: "Koshi",
    district: "Dhankuta",
    city: "Hile",
    departments: ["General Medicine"],
  },
  {
    name: "Bhojpur District Hospital",
    address: "Dingla, Bhojpur",
    latitude: 27.1667,
    longitude: 87.05,
    contactNumber: "",
    email: "bhojpurdistricthospiriamje@hospital.com.np",
    province: "Koshi",
    district: "Bhojpur",
    city: "Dingla",
    departments: ["General Medicine"],
  },
  {
    name: "Sankhuwasabha District Hospital",
    address: "Khandbari, Sankhuwasabha",
    latitude: 27.3667,
    longitude: 87.2167,
    contactNumber: "",
    email: "sankhuwasabhadistric9yl0nh@info.np",
    province: "Koshi",
    district: "Sankhuwasabha",
    city: "Khandbari",
    departments: ["General Medicine"],
  },
  {
    name: "Khotang District Hospital",
    address: "Diktel, Khotang",
    latitude: 27.1667,
    longitude: 86.8167,
    contactNumber: "",
    email: "khotangdistricthospif31irl@info.np",
    province: "Koshi",
    district: "Khotang",
    city: "Diktel",
    departments: ["General Medicine"],
  },
  {
    name: "Morang (Rangeli) Hospital",
    address: "Rangeli, Morang",
    latitude: 26.5333,
    longitude: 87.2833,
    contactNumber: "",
    email: "morangrangelihospita2y17dz@yahoo.com",
    province: "Koshi",
    district: "Morang",
    city: "Rangeli",
    departments: ["General Medicine"],
  },
  {
    name: "Sunsari District Hospital",
    address: "Inaruwa, Sunsari",
    latitude: 26.6167,
    longitude: 87.15,
    contactNumber: "",
    email: "sunsaridistricthospikxhgb5@yahoo.com",
    province: "Koshi",
    district: "Sunsari",
    city: "Inaruwa",
    departments: ["General Medicine"],
  },
  {
    name: "Udayapur District Hospital",
    address: "Gaighat, Udayapur",
    latitude: 26.9167,
    longitude: 86.2667,
    contactNumber: "035-420187",
    email: "udayapurdistricthosptgyt7f@yahoo.com",
    province: "Koshi",
    district: "Udayapur",
    city: "Gaighat",
    departments: ["General Medicine"],
  },
  {
    name: "Sindhuli Hospital",
    address: "Sindhulimadhi, Sindhuli",
    latitude: 27.2167,
    longitude: 86.0167,
    contactNumber: "9863330850",
    email: "shsindhuli132@gmail.com",
    province: "Bagmati",
    district: "Sindhuli",
    city: "Sindhulimadhi",
    departments: ["General Medicine"],
  },
  {
    name: "Chautara Hospital",
    address: "Chautara, Sindhupalchowk",
    latitude: 27.8167,
    longitude: 85.7167,
    contactNumber: "",
    email: "chautarahospitalownipp@hospital.com.np",
    province: "Bagmati",
    district: "Sindhupalchowk",
    city: "Chautara",
    departments: ["General Medicine"],
  },
  {
    name: "Trishuli Hospital",
    address: "Trishuli, Nuwakot",
    latitude: 27.9833,
    longitude: 85.2167,
    contactNumber: "",
    email: "trishulihospital28i4u3@gmail.com",
    province: "Bagmati",
    district: "Nuwakot",
    city: "Trishuli",
    departments: ["General Medicine"],
  },
  {
    name: "Dhading Hospital",
    address: "Dhading Besi, Dhading",
    latitude: 27.8167,
    longitude: 84.9167,
    contactNumber: "",
    email: "dhadinghospitalpkc184@info.np",
    province: "Bagmati",
    district: "Dhading",
    city: "Dhading Besi",
    departments: ["General Medicine"],
  },
  {
    name: "Gorkha Hospital",
    address: "Gorkha Bazaar, Gorkha",
    latitude: 28.0,
    longitude: 84.5333,
    contactNumber: "",
    email: "gorkhahospitalojd4ol@healthcare.np",
    province: "Gandaki",
    district: "Gorkha",
    city: "Gorkha",
    departments: ["General Medicine"],
  },
  {
    name: "Palpa Hospital",
    address: "Tansen, Palpa",
    latitude: 27.8667,
    longitude: 83.55,
    contactNumber: "",
    email: "palpahospitalwap1k8@gmail.com",
    province: "Lumbini",
    district: "Palpa",
    city: "Tansen",
    departments: ["General Medicine"],
  },
  {
    name: "Gulmi Hospital",
    address: "Tamghas, Gulmi",
    latitude: 28.0333,
    longitude: 83.2333,
    contactNumber: "",
    email: "gulmihospital153u9z@gmail.com",
    province: "Lumbini",
    district: "Gulmi",
    city: "Tamghas",
    departments: ["General Medicine"],
  },
  {
    name: "Arghakhachi Hospital",
    address: "Sandhikharka, Arghakhachi",
    latitude: 27.95,
    longitude: 83.0833,
    contactNumber: "",
    email: "arghakhachihospitalhcrj3d@gmail.com",
    province: "Lumbini",
    district: "Arghakhachi",
    city: "Sandhikharka",
    departments: ["General Medicine"],
  },
  {
    name: "Pyuthan Hospital",
    address: "Pyuthan, Pyuthan",
    latitude: 28.0833,
    longitude: 82.8833,
    contactNumber: "",
    email: "pyuthanhospitalth15k4@healthcare.np",
    province: "Lumbini",
    district: "Pyuthan",
    city: "Pyuthan",
    departments: ["General Medicine"],
  },
  {
    name: "Bardiya Hospital",
    address: "Gulariya, Bardiya",
    latitude: 28.2167,
    longitude: 81.3333,
    contactNumber: "",
    email: "bardiyahospitaln62nxb@hospital.com.np",
    province: "Lumbini",
    district: "Bardiya",
    city: "Gulariya",
    departments: ["General Medicine"],
  },
  {
    name: "Doti District Hospital",
    address: "Silgadhi, Doti",
    latitude: 29.2667,
    longitude: 80.9667,
    contactNumber: "",
    email: "dotidistricthospitaltmpybx@yahoo.com",
    province: "Sudurpashchim",
    district: "Doti",
    city: "Silgadhi",
    departments: ["General Medicine"],
  },
  {
    name: "Dadeldhura Hospital",
    address: "Amargadhi, Dadeldhura",
    latitude: 29.3,
    longitude: 80.5833,
    contactNumber: "",
    email: "dadeldhurahospital9u8u2f@gmail.com",
    province: "Sudurpashchim",
    district: "Dadeldhura",
    city: "Amargadhi",
    departments: ["General Medicine"],
  },
  {
    name: "Chandranigapur Hospital",
    address: "Chandranigahapur, Chandrapur, Rautahat",
    latitude: 26.9333,
    longitude: 85.6167,
    contactNumber: "+977-55-540150",
    email: "chandranigapurhospit2om0j5@healthcare.np",
    province: "Madhesh",
    district: "Rautahat",
    city: "Chandranigahapur",
    departments: ["General Medicine", "Emergency", "OPD"],
  },
  {
    name: "Burtibang Hospital",
    address: "Burtibang, Myagdi",
    latitude: 28.3167,
    longitude: 83.4167,
    contactNumber: "",
    email: "burtibanghospitaly68uvc@info.np",
    province: "Gandaki",
    district: "Myagdi",
    city: "Burtibang",
    departments: ["General Medicine"],
  },
  {
    name: "Rampur Hospital",
    address: "Rampur, Palpa",
    latitude: 27.6167,
    longitude: 83.6833,
    contactNumber: "",
    email: "rampurhospitaldjxzam@info.np",
    province: "Lumbini",
    district: "Palpa",
    city: "Rampur",
    departments: ["General Medicine", "Obstetrics"],
  },
  {
    name: "Banganga Hospital",
    address: "Banganga, Siraha",
    latitude: 26.8833,
    longitude: 86.2333,
    contactNumber: "",
    email: "bangangahospitalwz17e0@healthcare.np",
    province: "Madhesh",
    district: "Siraha",
    city: "Banganga",
    departments: ["General Medicine"],
  },
  {
    name: "Mehalkuna Hospital",
    address: "Mehalkuna, Sindhuli",
    latitude: 27.3167,
    longitude: 86.0167,
    contactNumber: "",
    email: "mehalkunahospitalmtv645@yahoo.com",
    province: "Bagmati",
    district: "Sindhuli",
    city: "Mehalkuna",
    departments: ["Primary Care"],
  },
  {
    name: "Tikapur Hospital",
    address: "Tikapur, Kailali",
    latitude: 28.5333,
    longitude: 80.9,
    contactNumber: "",
    email: "tikapurhospital1ehbsi@healthcare.np",
    province: "Sudurpashchim",
    district: "Kailali",
    city: "Tikapur",
    departments: ["General Medicine", "Emergency"],
  },
  {
    name: "Bakulahar Ratnanagar Hospital",
    address: "Ratnanagar, Chitwan",
    latitude: 27.6833,
    longitude: 84.45,
    contactNumber: "",
    email: "bakulaharratnanagarhapnfcr@yahoo.com",
    province: "Bagmati",
    district: "Chitwan",
    city: "Ratnanagar",
    departments: ["General Medicine"],
  },
  {
    name: "Bardibas Hospital",
    address: "Bardibas, Mahottari",
    latitude: 26.9167,
    longitude: 85.9167,
    contactNumber: "",
    email: "bardibashospital14kiil@info.np",
    province: "Madhesh",
    district: "Mahottari",
    city: "Bardibas",
    departments: ["General Medicine", "Surgery"],
  },
  {
    name: "Katari Hospital",
    address: "Katari, Udayapur",
    latitude: 26.8167,
    longitude: 86.2667,
    contactNumber: "",
    email: "katarihospitalvdf2y5@hospital.com.np",
    province: "Koshi",
    district: "Udayapur",
    city: "Katari",
    departments: ["General Medicine"],
  },
  {
    name: "Methinkot Hospital",
    address: "Methinkot, Sindhupalchowk",
    latitude: 27.7667,
    longitude: 85.6667,
    contactNumber: "",
    email: "methinkothospital7fd9g9@yahoo.com",
    province: "Bagmati",
    district: "Sindhupalchowk",
    city: "Methinkot",
    departments: ["Primary Care"],
  },
  {
    name: "Maninkhel Hospital",
    address: "Maninkhel, Lalitpur",
    latitude: 27.6333,
    longitude: 85.3,
    contactNumber: "",
    email: "maninkhelhospitalu4q0hp@info.np",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Maninkhel",
    departments: ["General Medicine"],
  },
  {
    name: "Mirchaiya Hospital",
    address: "Mirchaiya, Siraha",
    latitude: 26.7667,
    longitude: 86.5667,
    contactNumber: "",
    email: "mirchaiyahospitalbwvyyp@info.np",
    province: "Madhesh",
    district: "Siraha",
    city: "Mirchaiya",
    departments: ["General Medicine"],
  },
  {
    name: "Annapurna Neuro Hospital",
    address: "Shreeja Apartment, Lazimpat, Kathmandu",
    latitude: 27.7172,
    longitude: 85.324,
    contactNumber: "+977-1-4015520",
    email: "info@annapurnaneuro.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Neurology", "Neurosurgery", "Neuro ICU"],
  },
  {
    name: "Chitwan Medical College",
    address: "Bharatpur-10, Chitwan",
    latitude: 27.6333,
    longitude: 84.4333,
    contactNumber: "+977-56-511500",
    email: "info@chitwanmedicalcollege.edu.np",
    province: "Bagmati",
    district: "Chitwan",
    city: "Bharatpur",
    departments: ["General Medicine", "Surgery", "Pediatrics", "Gynecology"],
  },
  {
    name: "CIWEC Hospital",
    address: "Lazimpat, Kathmandu",
    latitude: 27.717,
    longitude: 85.33,
    contactNumber: "+977-1-4424111",
    email: "info@ciwec-clinic.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Emergency", "Travel Medicine", "Orthopedics"],
  },
  {
    name: "Janaki Medical College",
    address: "Janakpur, Dhanusha",
    latitude: 26.7289,
    longitude: 85.9249,
    contactNumber: "+977-41-522255",
    email: "janakimedicalcollege0ar64h@yahoo.com",
    province: "Madhesh",
    district: "Dhanusha",
    city: "Janakpur",
    departments: ["MBBS Teaching", "General Medicine"],
  },
  {
    name: "Kathmandu Medical College",
    address: "Sinamangal, Kathmandu",
    latitude: 27.7,
    longitude: 85.35,
    contactNumber: "+977-1-4469063",
    email: "kathmandumedicalcoll17doqc@gmail.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Teaching Hospital", "All Specialties"],
  },
  {
    name: "Kirtipur Hospital",
    address: "Kirtipur, Kathmandu",
    latitude: 27.6786,
    longitude: 85.2763,
    contactNumber: "+977-1-4331330",
    email: "kirtipurhospitaleokg4o@gmail.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kirtipur",
    departments: ["Orthopedics", "Trauma"],
  },
  {
    name: "Kist Medical College Teaching Hospital",
    address: "Imadol, Lalitpur",
    latitude: 27.65,
    longitude: 85.32,
    contactNumber: "+977-1-5252785",
    email: "kistmedicalcollegeteessab1@healthcare.np",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Imadol",
    departments: ["Teaching", "General Medicine"],
  },
  {
    name: "Kunde Hospital",
    address: "Kunde, Solukhumbu",
    latitude: 27.8,
    longitude: 86.7333,
    contactNumber: "",
    email: "kundehospital6cq91f@healthcare.np",
    province: "Koshi",
    district: "Solukhumbu",
    city: "Kunde",
    departments: ["General Medicine", "High Altitude"],
  },
  {
    name: "Manipal Teaching Hospital",
    address: "Phulbari, Pokhara",
    latitude: 28.2333,
    longitude: 83.9833,
    contactNumber: "+977-61-526400",
    email: "info@manipal.edu.np",
    province: "Gandaki",
    district: "Kaski",
    city: "Pokhara",
    departments: ["All Specialties", "Teaching"],
  },
  {
    name: "National Institute of Neurological Applied Science",
    address: "Bansbari, Kathmandu",
    latitude: 27.7667,
    longitude: 85.35,
    contactNumber: "+977-1-4373850",
    email: "national@neuro.org.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Neurology", "Neurosurgery"],
  },
  {
    name: "Nepal Medical Teaching Hospital",
    address: "Attarkhel, Jorpati, Gokarneshwor, Kathmandu",
    latitude: 27.7333,
    longitude: 85.3667,
    contactNumber: "+977-1-4911008",
    email: "nmc@nmcth.edu",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [
      "General Medicine",
      "Surgery",
      "Emergency",
      "ICU",
      "Teaching",
    ],
  },
  {
    name: "Nobel Medical College Teaching Hospital",
    address: "Biratnagar, Morang",
    latitude: 26.4525,
    longitude: 87.2718,
    contactNumber: "+977-21-534400",
    email: "info@nobelmed.com.np",
    province: "Koshi",
    district: "Morang",
    city: "Biratnagar",
    departments: ["MBBS Teaching", "All Specialties"],
  },
  {
    name: "Norvic Hospital",
    address: "Thapathali, Kathmandu",
    latitude: 27.6895,
    longitude: 85.322,
    contactNumber: "+977-1-4258554",
    email: "info@norvichospital.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Cardiology", "Orthopedics", "Emergency"],
  },
  {
    name: "Siddhartha Children and Women Hospital",
    address: "Butwal, Rupandehi",
    latitude: 27.7,
    longitude: 83.45,
    contactNumber: "+977-71-540080",
    email: "siddharthachildrenanrf2z2i@healthcare.np",
    province: "Lumbini",
    district: "Rupandehi",
    city: "Butwal",
    departments: ["Pediatrics", "Obstetrics", "Gynecology"],
  },
  {
    name: "Vayodha Hospital",
    address: "Khusibu, Kathmandu",
    latitude: 27.7333,
    longitude: 85.3,
    contactNumber: "+977-1-5911222",
    email: "vayodhahospitalaeqw15@gmail.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Orthopedics", "Emergency", "ICU"],
  },
  {
    name: "HAMS Hospital",
    address: "Dillibazar, Kathmandu",
    latitude: 27.7,
    longitude: 85.33,
    contactNumber: "+977-1-4444955",
    email: "info@hams.org.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Cardiology", "Gastroenterology"],
  },
  {
    name: "Himal Hospital",
    address: "Gyaneshwor, Kathmandu",
    latitude: 27.7167,
    longitude: 85.34,
    contactNumber: "+977-1-4424414",
    email: "himalhospitalsb1vzx@hospital.com.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["General Medicine", "Surgery"],
  },
  {
    name: "Inova Hospital",
    address: "Sitapaila, Kathmandu",
    latitude: 27.7333,
    longitude: 85.2667,
    contactNumber: "+977-1-4035966",
    email: "inovahospitala1u576@hospital.com.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Emergency", "Orthopedics"],
  },
  {
    name: "Siddhasthali Rural Community Hospital",
    address: "Siddhasthali, Lalitpur",
    latitude: 27.6333,
    longitude: 85.3167,
    contactNumber: "",
    email: "siddhasthaliruralcomivlfie@healthcare.np",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Siddhasthali",
    departments: ["Primary Care", "Community Health"],
  },
  {
    name: "Binaytara Foundation Cancer Center (BTFCC)",
    address: "Lalitpur",
    latitude: 27.6667,
    longitude: 85.3167,
    contactNumber: "+977-1-5530066",
    email: "binaytarafoundationckx5vun@gmail.com",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Lalitpur",
    departments: ["Oncology", "Chemotherapy"],
  },
  {
    name: "Saptakoshi Neuro Hospital",
    address: "Dharan, Sunsari",
    latitude: 26.8167,
    longitude: 87.2833,
    contactNumber: "+977-1-4911008",
    email: "nmc@nmcth.edu",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: [
      "General Medicine",
      "Surgery",
      "Emergency",
      "ICU",
      "Teaching",
    ],
  },
  {
    name: "Biratnagar Eye Hospital",
    address: "Biratnagar, Morang",
    latitude: 26.4525,
    longitude: 87.2718,
    contactNumber: "",
    email: "biratnagareyehospitamtdvvp@healthcare.np",
    province: "Koshi",
    district: "Morang",
    city: "Biratnagar",
    departments: ["Ophthalmology"],
  },
  {
    name: "Kathmandu Cancer Center Hospital",
    address: "Kathmandu",
    latitude: 27.7172,
    longitude: 85.324,
    contactNumber: "",
    email: "kathmanducancercentecy5piv@info.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Oncology", "Radiotherapy"],
  },
  {
    name: "Anandaban Hospital",
    address: "Leprosy Hospital Road, Kathmandu",
    latitude: 27.6833,
    longitude: 85.3,
    contactNumber: "+977-1-4271911",
    email: "anandabanhospitalbbyk6z@info.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Leprosy", "Rehabilitation"],
  },
  {
    name: "Om Hospital & Research Centre",
    address: "Chakrapath, Kathmandu",
    latitude: 27.7333,
    longitude: 85.35,
    contactNumber: "+977-1-5970576",
    email: "omhospitalresearchcen3eh91@hospital.com.np",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["Emergency", "ICU", "Cardiology"],
  },
  {
    name: "B & B Hospital",
    address: "Bhedasingh, Lalitpur",
    latitude: 27.6667,
    longitude: 85.3,
    contactNumber: "+977-1-5533206",
    email: "info@bbhospital.com.np",
    province: "Bagmati",
    district: "Lalitpur",
    city: "Lalitpur",
    departments: ["IVF", "NICU", "Emergency"],
  },
  {
    name: "Purbanchal Cancer Hospital",
    address: "Dharan, Sunsari",
    latitude: 26.8167,
    longitude: 87.2833,
    contactNumber: "",
    email: "purbanchalcancerhospuvid82@healthcare.np",
    province: "Koshi",
    district: "Sunsari",
    city: "Dharan",
    departments: ["Oncology"],
  },
  {
    name: "B&C Medical College Teaching Hospital and Research Center",
    address: "Jhapa",
    latitude: 26.4167,
    longitude: 88.0,
    contactNumber: "",
    email: "bcmedicalcollegeteaccgnv0m@info.np",
    province: "Koshi",
    district: "Jhapa",
    city: "Birtamod",
    departments: ["Teaching", "General Medicine"],
  },
  {
    name: "STD Treatment Clinic",
    address: "Kathmandu",
    latitude: 27.7172,
    longitude: 85.324,
    contactNumber: "",
    email: "stdtreatmentclinicxncaje@gmail.com",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    departments: ["STD Treatment", "Dermatology"],
  },
];

async function seed() {
  console.log("Seeding hospitals...");

  const client = postgres(process.env.SUPABASE_DATABASE_URL!, {
    prepare: false,
  });
  const db = drizzle(client, { schema });

  for (const hospitalData of nepalHospitals) {
    const { departments, ...hospital } = hospitalData;

    try {
      // Check if hospital already exists
      const existing = await db
        .select({ id: schema.hospitals.id })
        .from(schema.hospitals)
        .where(eq(schema.hospitals.name, hospital.name));

      let hospitalId = existing[0]?.id;

      if (!hospitalId) {
        // Insert hospital
        const [insertedHospital] = await db
          .insert(schema.hospitals)
          .values(hospital)
          .returning({ id: schema.hospitals.id });
        hospitalId = insertedHospital.id;
        console.log(`Inserted ${hospital.name} with ID: ${hospitalId}`);
      } else {
        console.log(`Skipping ${hospital.name} (already exists)`);
      }

      // Insert departments & doctors only if new hospital (simplification for now, or check for them too)
      // For this task, strict idempotency on child tables is harder without unique names per hospital.
      // But if we skipped hospital insert, we likely already seeded it.
      if (!existing[0] && departments.length > 0) {
        const departmentValues = departments.map((deptName) => ({
          hospitalId: hospitalId!,
          name: deptName,
        }));

        const insertedDepartments = await db
          .insert(schema.hospitalDepartments)
          .values(departmentValues)
          .returning();

        console.log(
          `  Inserted ${departments.length} departments for ${hospital.name}`
        );

        // Seed Doctors
        const firstNames = [
          "Dr. Aarav",
          "Dr. Diya",
          "Dr. Arjun",
          "Dr. Saira",
          "Dr. Vivaan",
          "Dr. Myra",
          "Dr. Reyansh",
          "Dr. Ananya",
        ];
        const lastNames = [
          "Sharma",
          "Verma",
          "Gupta",
          "Malhotra",
          "Bhatia",
          "Saxena",
          "Mehta",
          "Chopra",
        ];

        for (const dept of insertedDepartments) {
          const numDoctors = Math.floor(Math.random() * 3) + 2; // 2-4 doctors per department
          const doctorValues = Array.from({ length: numDoctors }).map(() => ({
            name: `${
              firstNames[Math.floor(Math.random() * firstNames.length)]
            } ${lastNames[Math.floor(Math.random() * lastNames.length)]}`,
            hospitalDepartmentId: dept.id,
            dailyCapacity: Math.floor(Math.random() * 10) + 5, // 5-15 daily capacity
          }));

          await db.insert(schema.doctors).values(doctorValues);
        }
        console.log(`  Seeded doctors for ${hospital.name}`);
      }
    } catch (error) {
      console.error(`Error processing ${hospital.name}:`, error);
    }
  }

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
